#173 update example for Yew
plotly/plotly.rs pull request #174
Opened 2023-12-12 04:42 UTC by yunaka354

Solve #173 

Please let me know if I need to fix something else. I am happy to take another action.

2024-05-26 03:57 UTC, youngday reviewed
update yew to 0.21.0

2024-05-26 03:58 UTC, youngday requested changes
update yew to 0.21.0

2024-05-26 04:03 UTC, youngday approved these changes
update yew to 0.21.0

2024-06-18 11:53 UTC, andrei-ng approved these changes

2024-06-18 11:57 UTC, merged